### ISSUE TITLE
使用longtable以处理长表格的跨页问题

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#11]
https://www.ctan.org/pkg/longtable

**Comment by wangliang1989** [comment]
你是要我用longtable吗

**Comment by seisman** [comment]
暂时可能不需要，因为“震相拾取”一节在我修改之后，已经不会因为表的存在而导致出现空白了。所以目前暂时不需要，但是考虑到以后排版的灵活性，可能还需要使用longtable。这个事情可以推迟。

**Comment by wangliang1989** [comment]
恩，好的。你改的很好，我句子啰嗦了。我觉得续表的方式不太常见，不是特别理想。

**Comment by seisman** [comment]
longtable一般在表格超过一页的时候才会用到，不过有时候为了避免表格的float导致页面出现大量空白，应该也会采取类似的做法。

**Comment by wangliang1989** [comment]
我觉得应该都用longtable，免得每次都要调整。或者可以自动生成续表

**Comment by seisman** [comment]
恩，longtable就可以自动生成续表。印象中我原来就是用longtable的，但是不知道什么时候被我删除了。

**Comment by wangliang1989** [comment]
如果longtable难看，还是现在的好，也可以人工调

**Comment by seisman** [comment]
Fixed in 3cf1bd60d59589c3f5cbbf79ac58e41be099f1ac
