### ISSUE TITLE
rst中文段落换行导致生成的html多出空格

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [seisman/SAC_Docs_zh#120]
在谷歌浏览器、360浏览器、IE浏览器中都会多出空格；
在火狐浏览器中没有多出空格。

**Comment by seisman** [comment]
产生多余空格的主要原因是因为在rst源码中出现换行导致的，最根本原因是因为rst在最初设计时没有考虑中文的情况。

参考链接：
1. http://www.voidcn.com/article/p-ricojlou-or.html
2. https://stackoverflow.com/questions/8550112/
