### ISSUE TITLE
网页链接风格

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#129]
目前网页链接的最后是以 `.html` 结尾的，例如 https://seisman.github.io/SAC_Docs_zh/call-in-script/call-sac-in-bash.html

目前更主流的链接地址是不以 `.html` 结尾，即 https://seisman.github.io/SAC_Docs_zh/call-in-script/call-sac-in-bash/

是否需要更换为新的URL

**Comment by wangliang1989** [comment]
确实是现在html结尾过时了，我倾向于删除

**Comment by zhaozhiyuan1989** [comment]
同意替换。Hugo能够自主选择链接风格，不知道sphinx可不可以？

**Comment by seisman** [comment]
@wangliang1989 @zhaozhiyuan1989 已经替换。

使用 `make html` 生成原来风格的链接；使用 `make dirhtml` 生成不带 `.html` 风格的链接。

但是不带 `.html` 风格的链接无法直接预览，可以使用 make serve 然后浏览器打开 `localhost:8000` 实现预览。
