### ISSUE TITLE
sac中存在的2个bug

### ISSUE THREAD

**Issue by junlysky** [seisman/SAC_Docs_zh#13]
发现SAC命令调用时存在的2个“bug”：

1. READ读取子文件夹中的数据，若文件夹的名字以"dir" 开头，语句" r dir/*.SAC"无法读取数据,需在文件夹"dir"前加 "./"  
    ```
    SAC> READ dir/seis.sac                # ERROR 1301: No data files read in.
    SAC> READ ./dir/seis.sac              # OK
    ```

2. perl脚本中调用SAC命令，可用 qq[ ] 代替双引号，以减少键入，此时要注意：qq[ ]中可以有空格符号，但是不可以有“TAB”符号，
    ```
    open(SAC, "| sac ") or die "Error opening sac ";
    print  SAC qq [
        read  ./$dir/$sacfile  \n];              # wrong            

    print  SAC qq [
    read  ./$dir/$sacfile  \n];                  # ok
    ```

**Comment by seisman** [comment]
8ae7d10b42e4fe86a7ad3c8ec1e5b173fdbffa37 ，此次commit增加了对第一个bug的解释，你可以看一下，有没有什么需要补充的地方。

**Comment by junlysky** [comment]
good！可将q[ ] 部分也加入～

Date: Tue, 5 May 2015 08:28:21 -0700

**Comment by seisman** [comment]
Tab键的问题已添加到文档中(764087184cd118be89cd0715e7c90c2b149ce51b)
