### ISSUE TITLE
issues of merge scripts

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#135]
Issue reported by a SAC user:

> 试了一下seisman的2.merge.py脚本，有一个bug，在merge那一行，如果数据段之间存在重叠，最后会导致merge不成功，而数据仍然会被删除，这个贸然使用会导致严重后果，我试了将merge改为merge overlap average 可以避免这个问题
> 
> 另外，对于大数据量，glob不适用，可以试用fnmatch，亲测可用，一次性merge了380000个文件

**Comment by wangliang1989** [comment]
glob不适用 这个说法不理解啊，他意思好像是超过了glob能处理的文件个数

**Comment by core-man** [comment]
- 目前的 `merge gap zero overlap average` 没有数据误删问题。
- 对于绝大部用户，`merge` 的文件不会很多，无非修改。

我们可以关闭这个 issue 了吗 @seisman @wangliang1989

**Comment by wangliang1989** [comment]
102版sac取消了读入文件数量的限制
