### ISSUE TITLE
两个 resp 文件转换为 PZ 文件

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#139]
地震仪包含了地震计（Sensor）和数采（Datalogger）两个部分。
事实上，地震计和数采分别有一个 resp 文件。
没错，这和平时直接用 seed 转换出来一个 SAC 文件对应一个仪器响应文件的情况不同，
这就是两个 resp 文件转换为 PZ 文件的需求来源。
和单个 resp 文件转换为 PZ 文件的情形基本一样，不同点为：

#. PZ 文件的零点、极点部分由地震计的 resp 文件的零点、极点决定，而与数采无关。具体如何得到，和前面单个 resp 文件的情形相同。
#. PZ 文件中的 CONSTANT 是地震计的 A0、地震计的仪器灵敏度 Sensitivity 和数采的仪器灵敏度 Sensitivity 三者的乘积。

**以上内容，不确定的为零极点是否和数采无关**

**Comment by core-man** [comment]
使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。

**Comment by wangliang1989** [comment]
> 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。

这个问题我们当时好像解决了的。在手册里有怎么自己写resp文件。

**Comment by core-man** [comment]
Close the issue?

**Comment by wangliang1989** [comment]
> Close the issue?

需要seisman确认下我的理解对不对。

**Comment by wangliang1989** [comment]
resp的问题还有一个问题。有测试文件，如何写resp

**Comment by core-man** [comment]
> resp的问题还有一个问题。有测试文件，如何写resp

我没理解你的问题，可否单独提交一个 issue，描述一下？

**Comment by core-man** [comment]
> > Close the issue?
> 
> 需要seisman确认下我的理解对不对。

我看了一下[物理与数学](https://seisman.github.io/SAC_Docs_zh/appendix/resp/physical-details/)，原理上没问题。实际上新手可能不知道有两个resp文件。

**Comment by seisman** [comment]
> > 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。
> 
> 这个问题我们当时好像解决了的。在手册里有怎么自己写resp文件。

我在手册里没有找到关于如何“手写resp”的相关内容。而且 resp 本身非常复杂，手写不太现实，倒是手写 SAC PZ 相对简单一些。

**Comment by wangliang1989** [comment]
> > > 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。
> > 
> > 
> > 这个问题我们当时好像解决了的。在手册里有怎么自己写resp文件。
> 
> 我在手册里没有找到关于如何“手写resp”的相关内容。而且 resp 本身非常复杂，手写不太现实，倒是手写 SAC PZ 相对简单一些。

是手写PZ

**Comment by seisman** [comment]
> 是手写PZ

在哪？

**Comment by wangliang1989** [comment]
> > 是手写PZ
> 
> 在哪？
B.3.6

**Comment by wangliang1989** [comment]
> 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。

我接触国产仪器比较多。国产仪器都是采集器和地震仪是同一个企业做的，搭配使用。为什么国外的仪器会出现采集器和地震仪不同的问题？国外的仪器，地震仪在测量的时候，采集器和地震仪不连接吗？可不可以给我讲解一下？

另外，其实每一个地震仪都是独一无二的，都有独一无二的response，你会不会为某一台地震仪制作仪器响应文件？可不可以帮帮我

**Comment by core-man** [comment]
> > 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。
> 
> 我接触国产仪器比较多。国产仪器都是采集器和地震仪是同一个企业做的，搭配使用。为什么国外的仪器会出现采集器和地震仪不同的问题？国外的仪器，地震仪在测量的时候，采集器和地震仪不连接吗？可不可以给我讲解一下？

布台的时候肯定是要有采集器和地震仪的，至于时不是同一家厂商无所谓了。但是仪器响应的原理是类似的，有个两个resp就可以拼在一块就行了。

> 另外，其实每一个地震仪都是独一无二的，都有独一无二的response，你会不会为某一台地震仪制作仪器响应文件？可不可以帮帮我

每个仪器是独一无二的，一般仪器商会提供。没有的话我们可以参考http://ds.iris.edu/NRL/，基本常见的地震仪和数采都有了。

**Comment by wangliang1989** [comment]
> > > 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。
> > 
> > 
> > 我接触国产仪器比较多。国产仪器都是采集器和地震仪是同一个企业做的，搭配使用。为什么国外的仪器会出现采集器和地震仪不同的问题？国外的仪器，地震仪在测量的时候，采集器和地震仪不连接吗？可不可以给我讲解一下？
> 
> 布台的时候肯定是要有采集器和地震仪的，至于时不是同一家厂商无所谓了。但是仪器响应的原理是类似的，有个两个resp就可以拼在一块就行了。
> 
> > 另外，其实每一个地震仪都是独一无二的，都有独一无二的response，你会不会为某一台地震仪制作仪器响应文件？可不可以帮帮我
> 
> 每个仪器是独一无二的，一般仪器商会提供。没有的话我们可以参考[http://ds.iris.edu/NRL/，基本常见的地震仪和数采都有了。](http://ds.iris.edu/NRL/%EF%BC%8C%E5%9F%BA%E6%9C%AC%E5%B8%B8%E8%A7%81%E7%9A%84%E5%9C%B0%E9%9C%87%E4%BB%AA%E5%92%8C%E6%95%B0%E9%87%87%E9%83%BD%E6%9C%89%E4%BA%86%E3%80%82)

NRL上面的针对的是设备的型号。我的意思是每一台设备的响应其实都不同，我有标定的文件。但是不知道如何写成PZ或者RESP

**Comment by wangliang1989** [comment]
> > > 使用移动台数据时，经常会遇到这个问题。比如可能野外可能使用[Nanometrics Trillium](http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html)地震计和[DiGOS/Omnirecs](http://ds.iris.edu/NRL/dataloggers/omnirecs/omnirecs_datacube_dataloggers.html)数采。
> > 
> > 
> > 我接触国产仪器比较多。国产仪器都是采集器和地震仪是同一个企业做的，搭配使用。为什么国外的仪器会出现采集器和地震仪不同的问题？国外的仪器，地震仪在测量的时候，采集器和地震仪不连接吗？可不可以给我讲解一下？
> 
> 布台的时候肯定是要有采集器和地震仪的，至于时不是同一家厂商无所谓了。但是仪器响应的原理是类似的，有个两个resp就可以拼在一块就行了。
> 
> > 另外，其实每一个地震仪都是独一无二的，都有独一无二的response，你会不会为某一台地震仪制作仪器响应文件？可不可以帮帮我
> 
> 每个仪器是独一无二的，一般仪器商会提供。没有的话我们可以参考[http://ds.iris.edu/NRL/，基本常见的地震仪和数采都有了。](http://ds.iris.edu/NRL/%EF%BC%8C%E5%9F%BA%E6%9C%AC%E5%B8%B8%E8%A7%81%E7%9A%84%E5%9C%B0%E9%9C%87%E4%BB%AA%E5%92%8C%E6%95%B0%E9%87%87%E9%83%BD%E6%9C%89%E4%BA%86%E3%80%82)

你们国外的仪器买了，没有标定文件吗？

**Comment by core-man** [comment]
没懂你在说啥，iris给了具体型号的resp，我用过他的地震计和树采resp凑成一个pz

**Comment by wangliang1989** [comment]
> 没懂你在说啥，iris给了具体型号的resp

比如有两台地震仪，型号是完全一样的，但是实际上他们的response也是不一样的。真实的respoonse需要定期标定

**Comment by core-man** [comment]
> > 没懂你在说啥，iris给了具体型号的resp
> 
> 比如有两台地震仪，型号是完全一样的，但是实际上他们的response也是不一样的。真实的respoonse需要定期标定

型号一样response不同，还能算一个型号吗？

**Comment by wangliang1989** [comment]
> > > 没懂你在说啥，iris给了具体型号的resp
> > 
> > 
> > 比如有两台地震仪，型号是完全一样的，但是实际上他们的response也是不一样的。真实的respoonse需要定期标定
> 
> 型号一样response不同，还能算一个型号吗？

你可能没有认真上大物实验。物理测量仪器严格说每一台都是不同的。严格说都需要定期标定。

**Comment by core-man** [comment]
> > > > 没懂你在说啥，iris给了具体型号的resp
> > > 
> > > 
> > > 比如有两台地震仪，型号是完全一样的，但是实际上他们的response也是不一样的。真实的respoonse需要定期标定
> > 
> > 
> > 型号一样response不同，还能算一个型号吗？
> 
> 你可能没有认真上大物实验。物理测量仪器严格说每一台都是不同的。严格说都需要定期标定。

这种级别的差异有本质影响吗？仪器都是有严格的设计参数的，每台仪器是可能不同，但这个不同是应该在设计参数浮动范围之内。中国科大物理类专业是要上4个学期的大学物理实验。

**Comment by wangliang1989** [comment]
> > > > > 没懂你在说啥，iris给了具体型号的resp
> > > > 
> > > > 
> > > > 比如有两台地震仪，型号是完全一样的，但是实际上他们的response也是不一样的。真实的respoonse需要定期标定
> > > 
> > > 
> > > 型号一样response不同，还能算一个型号吗？
> > 
> > 
> > 你可能没有认真上大物实验。物理测量仪器严格说每一台都是不同的。严格说都需要定期标定。
> 
> 这种级别的差异有本质影响吗？仪器都是有严格的设计参数的，每台仪器是可能不同，但这个不同是应该在设计参数浮动范围之内。中国科大物理类专业是要上4个学期的大学物理实验。

你没有实际考察，怎么知道影响大小呢

**Comment by core-man** [comment]
出于对仪器公司的信任。此外，一般用宽频带仪器在虑波频段是flat的，影响不大。如果用的短周期或者超短周期仪器，研究的信号频率要是低于10-20秒，那就要小心一点了。

**Comment by wangliang1989** [comment]
> 出于对仪器公司的信任。此外，一般用宽频带仪器在虑波频段是flat的，影响不大。如果用的短周期或者超短周期仪器，研究的信号频率要是低于10-20秒，那就要小心一点了。

你说滤波频段是平的，意思是不是他对于一定频率范围内的信号的响应是相通的？
为什么是这样，就不太需要担心？
你是说频率大于0.1Hz？或者大于0.5Hz。为什么频率大于这个值就要当心呢？

**Comment by core-man** [comment]
> > 出于对仪器公司的信任。此外，一般用宽频带仪器在虑波频段是flat的，影响不大。如果用的短周期或者超短周期仪器，研究的信号频率要是低于10-20秒，那就要小心一点了。
> 
> 你说滤波频段是平的，意思是不是他对于一定频率范围内的信号的响应是相通的？
> 为什么是这样，就不太需要担心？
> 你是说频率大于0.1Hz？或者大于0.5Hz。为什么频率大于这个值就要当心呢？

不同周期仪器的响应与仪器设计和使用范围有很大的关系。

你说的每个仪器响应不同，严格来说是这样的。但是对于实际情况来说（以下是我个人数据处理的个人经验）：
1）仪器有设计规格，如果生产出来的仪器差异很大，是不合理的；
2）仪器布射前后都会有专业人员进行维护和调整；
3）实际研究中，如果仪器是同一种型号且设置参数都相同，我认为是在近flat的响应范围内，大部分时候是可以用同一个仪器响应的；
4）如果有仪器明显响应除了问题，可以回头单独调整和更换

仪器这一块很复杂，也是地震学参考书的计划内容，不过优先级比较低：https://github.com/seismo-learn/maintenance/issues/13。

**Comment by core-man** [comment]
@wangliang1989 你说的标定文件，我并不理解指得是啥。

**Comment by wangliang1989** [comment]
> @wangliang1989 你说的标定文件，我并不理解指得是啥。

我就是看不懂，我有那个文件

**Comment by core-man** [comment]
> > @wangliang1989 你说的标定文件，我并不理解指得是啥。
> 
> 我就是看不懂，我有那个文件

要不你打开一个新的issue，展示一下文件和相关信息？
我们每个人有空的时候都可以思考一下。

**Comment by core-man** [comment]
@wangliang1989 Davis 在
https://doi.org/10.1785/gssrl.76.6.678 对GSN台的仪器响应进行过评估。Hutt 和 Ringler在 https://doi.org/10.1785/gssrl.82.4.560 讨论了可能的原因。我没细读，你有兴趣的话，可以参考一下。

**Comment by wangliang1989** [comment]
> @wangliang1989 Davis 在
> https://doi.org/10.1785/gssrl.76.6.678 对GSN台的仪器响应进行过评估。Hutt 和 Ringler在 https://doi.org/10.1785/gssrl.82.4.560 讨论了可能的原因。我没细读，你有兴趣的话，可以参考一下。

谢谢，我以后会看看
我这段时间在写论文，其他都暂停了
