### ISSUE TITLE
怎么处理一个很长久的改善任务

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#14]
翻译readcss命令，需要英翻汉，然后还需要用数据试一试，中间还有一些解决不了的问题。
1这些都不可能一时解决，需要一个较长的时间，但是我又希望其他贡献者能看到我工作的进度，提出一些建议、指导和纠正。
2我可能遇到一些解决不了的问题，比如翻译时遇到的语言问题，我希望其他参与者能协助解决
我不知道这两点该怎么操作

**Comment by wangliang1989** [comment]
还有怎么给issue添加label

**Comment by seisman** [comment]
首先还是新建分支，然后提交你所做的改动，并发起pull request，这样你之后在这个分支里的提交我都可以看到，就可以给你提意见。如果整个完成了，就可以merge了。

**Comment by wangliang1989** [comment]
还有怎么给issue添加label

**Comment by seisman** [comment]
每个Issue的右边不是有个Labels么，点那个齿轮就可以加Label了，但是我不确定在我的repo下你有没有加label的权限。

**Comment by wangliang1989** [comment]
恩，没有权限
