### ISSUE TITLE
手册对头段变量idep的描述不符合事实

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#143]
![6242549a727b729607c6e6684326cc9d](https://user-images.githubusercontent.com/12059719/50384450-b1bea800-06ff-11e9-958a-332789ea648c.jpg)
sac的显示方式如上，与手册描述的有差异 @wangliang1989

**Comment by seisman** [comment]
哪里不一致？

**Comment by wangliang1989** [comment]
比如saclst出来的结果是数字，手册里没有提

**Comment by seisman** [comment]
意义不大。1. IDEP的值不可信，且几乎没人会需要去判断IDEP的值；2. IDEP的值为7，如果真的要在手册里说清楚太麻烦。
