### ISSUE TITLE
完善安装部分

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#148]
以下问题有经验的人没问题，初学者很难自己解决

1. 修改环境变量这一步强调地不够。
2. 自行编译和直接使用可执行文件的差异没有交代清。初学者可能误以为二者需要同时做。
3. 安装部分归于简介的一部分。这个位置似乎不太合理因为初学者可能会需要直接去找安装。
4. IRIS 分发的软件包更改了名字。

**Comment by core-man** [comment]
> 1. 修改环境变量这一步强调地不够。

#184 建议修改环境变量单独一节

> 2. 自行编译和直接使用可执行文件的差异没有交代清。初学者可能误以为二者需要同时做。

#184 建议按照**二进制包**和**源码包**安装分两小节，而不是macOS和Linux两小节

> 3. 安装部分归于简介的一部分。这个位置似乎不太合理因为初学者可能会需要直接去找安装。

done in #175. 新建了安装一章

> 4. IRIS 分发的软件包更改了名字。

?

---

如果以上问题已解决或者在其他issue里会解决，我们关闭这个 issue？
