### ISSUE TITLE
改善简介和基础的目录

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#160]
- 建议将[申请 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/request/)、[Linux 下安装 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/linux-install/)、[macOS 下安装 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/macOS-install/) 单独成章节**安装 SAC**

- [如何阅读本文档？](https://seisman.github.io/SAC_Docs_zh/basis/how-to-read/)和
[文档约定](https://seisman.github.io/SAC_Docs_zh/basis/convection/)移动到**SAC 简介**下？

- [SAC 基础](https://seisman.github.io/SAC_Docs_zh/basis/)重命名为**入门教程**？

**Comment by core-man** [comment]
@wangliang1989 正在 #158 修改mac下SAC安装，涉及到排版问题，我们应该首先讨论这个 issue。Ping @seisman @wangliang1989 的意见？

**Comment by seisman** [comment]
> * 建议将[申请 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/request/)、[Linux 下安装 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/linux-install/)、[macOS 下安装 SAC](https://seisman.github.io/SAC_Docs_zh/introduction/macOS-install/) 单独成章节**安装 SAC**

OK.

> * [SAC 基础](https://seisman.github.io/SAC_Docs_zh/basis/)重命名为**入门教程**？

这取决于这一节是否要新增更多的内容。目前的内容很难称得上是“入门”教程。

**Comment by core-man** [comment]
> > * [SAC 基础](https://seisman.github.io/SAC_Docs_zh/basis/)重命名为**入门教程**？
> 
> 这取决于这一节是否要新增更多的内容。目前的内容很难称得上是“入门”教程。

基本不就更难匹配了。

**Comment by core-man** [comment]
> * [如何阅读本文档？](https://seisman.github.io/SAC_Docs_zh/basis/how-to-read/)和
>   [文档约定](https://seisman.github.io/SAC_Docs_zh/basis/convection/)移动到**SAC 简介**下？

Ping @seisman for comment?

**Comment by seisman** [comment]
> * [如何阅读本文档？]

Yes.

> [文档约定](https://seisman.github.io/SAC_Docs_zh/basis/convection/)

Some of the contents may make no sense to the reader until they read the next chapter.

**Comment by core-man** [comment]
> > * [如何阅读本文档？]
> 
> Yes.
> 
> > [文档约定](https://seisman.github.io/SAC_Docs_zh/basis/convection/)
> 
> Some of the contents may make no sense to the reader until they read the next chapter.

I still think it's strange to put the subsection in SAC basis.

**Comment by seisman** [comment]
OK, let's move it to the end of the introduction chapter.
