### ISSUE TITLE
SAC 102 迁移策略？

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#162]
三种不同的迁移策略：

1. master分支不再更新，所有PR都提交到 `102` (建议改名为 `dev`) 分支，待完成迁移后将 dev 合并到 master
2. 迁移过程中，所有针对 SAC v102 的改动提交到 dev，其他修改（比如修bug，整理文档结构、增删内容）提交到master分支。待dev成熟后，master分支发布v4.2版本，然后dev合并到master，发布v5.0
3. 直接所有更新提交到 master 分支

需要注意的是，与 gmt-china/GMT_docs 不同，SAC中文手册网页版只有一个版本，所以当更新到SAC v102之后，使用 SAC v106.a 的用户只能读老版本PDF。

**Comment by core-man** [comment]
> 2. 迁移过程中，所有针对 SAC v102 的改动提交到 dev，其他修改（比如修bug，整理文档结构、增删内容）提交到master分支。
待dev成熟后，master分支发布v4.2版本，然后dev合并到master，发布v5.0

我支持 2 号，这样我们可以一直维护101.6的最新版本。#158 里的一些修改就需要提交单独提交 PR，merge 到 master 分支中。

**Comment by seisman** [comment]
2号的缺点在于，需要每个PR尽量小，且PR的提交者要清楚自己的改动是针对于master还是dev

我目前不清楚迁移到 SAC v102 有多大的工作量，也无法预估这个过程会持续多久。

**Comment by core-man** [comment]
> 2号的缺点在于，需要每个PR尽量小，且PR的提交者要清楚自己的改动是针对于master还是dev
> 
> 我目前不清楚迁移到 SAC v102 有多大的工作量，也无法预估这个过程会持续多久。

如果该手册不是未来主要维护目标，那我们可以直接选择 1 号吧。我们可以近期对101.6做一系列修改，发布一个最终版。然后在一起维护一个不知道多长时间、多长工作量的102版本。@wangliang1989 觉得呢？

**Comment by wangliang1989** [comment]
我支持2号方案

**Comment by wangliang1989** [comment]
用户从101.6迁移到102几乎零成本吧，又有什么成本呢？

**Comment by seisman** [comment]
我目前倾向于2号方案。

**Comment by seisman** [comment]
我创建了 dev 分支，所有与 SAC v102 无关的修改都合并到 master 分支，与 SAC v102 相关的修改合并到 dev 分支。

提交 PR 的时候请使得每个 PR 尽量小，且注意选择目标分支。
