### ISSUE TITLE
Add workflows for previewing PRs

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#166]
See https://github.com/gmt-china/GMT_docs/pull/186

**Comment by seisman** [comment]
We can use vercel, since the repository is in my personal account.

**Comment by core-man** [comment]
> We can use vercel, since the repository is in my personal account.

good~

**Comment by seisman** [comment]
First preview: https://sac-docs-zh.vercel.app/

You should be able to see the preview site in your next PR.
