### ISSUE TITLE
macOS 下 ~/.bash_profile 应改成 ~/.zshrc

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#179]
新版本 macOS 默认使用 zsh

**Comment by core-man** [comment]
@wangliang1989 直接小改一下解决这个issue先？

**Comment by wangliang1989** [comment]
你现在改了，master和dev就改了同一个文件了，咋整？

**Comment by core-man** [comment]
> 你现在改了，master和dev就改了同一个文件了，咋整？

我觉得没事的。dev现在跟master基本一样。我们只是加了一点102的修改而已（https://github.com/seisman/SAC_Docs_zh/pull/174/files）

**Comment by seisman** [comment]
我会负责解决dev与master的冲突问题。当冲突到了无法解决的时候，就可以发布新版本了

**Comment by wangliang1989** [comment]
> 我会负责解决dev与master的冲突问题。当冲突到了无法解决的时候，就可以发布新版本了

git历史乱的

**Comment by seisman** [comment]
不会乱

**Comment by wangliang1989** [comment]
如果你们觉得可以，我可以分别向dev和master发pr改zshrc

**Comment by core-man** [comment]
> 如果你们觉得可以，我可以分别向dev和master发pr改zshrc

只需要master就可以了，因为这个与v102无关。
