### ISSUE TITLE
将如何维护手册放在手册中

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#18]
参考：http://seisman.info/maintainers-for-sac-manual-wanted.html
位置：维护者列表后，或者附录中

**Comment by wangliang1989** [comment]
把维护者列表、招募维护者和如何维护放在一起，要能在目录看到。现在的维护者列表、版本说明那些都在目录里看不到，别人可能就注意不到

**Comment by seisman** [comment]
封面与目录之间，现在已有的内容有：序言、版本说明、维护者列表。要增加“维护者招募”和“如何维护”两部分。这部分的内容估计会写两页以上，但还没想好要要放在什么位置。

**Comment by wangliang1989** [comment]
维护者列表放到招募里，招募放到版本说明后，另起一节（章），醒目一些，然后如何参与维护放到附录里（招募里给一个链接）。

**Comment by seisman** [comment]
我不太想将如何参与放在附录中，因为目前附录中的内容都是一些与SAC有关，但关联又不太大的一些知识点，把如何参与放在附录里有些太突兀了。

**Comment by wangliang1989** [comment]
那就跟在版本说明后面，然后维护者列表也放在招募里

**Comment by wangliang1989** [comment]
参与维护的障碍有很多，虽然这些知识要求不深，但是都有的人比较少

**Comment by wangliang1989** [comment]
可以强调欢迎报错

**Comment by seisman** [comment]
参与的方式有三种：
1. 邮件报告文档中的错误；
2. 在项目主页上提交Issue；
3. Fork该项目并提交PR；

对于前两个来说，基本不需要啥知识。只有第三点需要掌握Git和LaTeX。如果只是简单的改错字什么的，甚至LaTeX都不需要掌握。

BTW：好像还要介绍一下LaTeX。。。

**Comment by wangliang1989** [comment]
告诉读者现在文档不完善的地方，他们可以写，然后发过来，可以在邮件里写，也可以在issue里写

在 2015年8月18日 下午10:21，Dongdong Tian notifications@github.com写道：

**Comment by seisman** [comment]
目前的想法：

维护者列表放在前面，把如何维护放在最后（可能是在附录里，也可能是在附录之后）然后在维护者列表那里加几句话以及指向“如何维护”的链接。

如何维护里，会介绍LaTeX的安装、源码的结构、如何编译、维护的三种方式（主要介绍第三种）。

**Comment by wangliang1989** [comment]
latex的安装、源码的结构都写是不是太啰嗦了？这个要写，怎么安装centos要不要写呢？不可能把每一步都介绍清楚。你博客里有怎么安装latex，给一个链接就可以了。源码的结构在github上有。
如果愿望很强，可以按照指导逐步学习。如果没有什么愿望，可以发邮件。

在 2015年8月18日 下午10:32，Dongdong Tian notifications@github.com写道：

**Comment by seisman** [comment]
CentOS对于这个文档不是必须的，而LaTeX对于这个文档则是必须的。

如果按照我上面提到的想法，将如何维护放在单独文档的最后，相对来说就可以写很长。而且上面所列举的内容中，其实只有维护的第三种方式需要详细介绍，而第三种方式很可能要写很长。把其他知识点补充完整是为了避免头轻脚重。

**Comment by wangliang1989** [comment]
好吧。
维护者列表放在前面，把如何维护放在最后（可能是在附录里，也可能是在附录之后）
那招募写在哪里呢？
招募就和维护者列表一起吧。

在 2015年8月18日 下午10:43，Dongdong Tian notifications@github.com写道：

**Comment by seisman** [comment]
招募其实就几句话，跟维护者列表放在一起。

**Comment by wangliang1989** [comment]
恩，写得引诱人一些。

2015-08-18 22:50 GMT+08:00 Dongdong Tian notifications@github.com:

**Comment by seisman** [comment]
Fixed in #26, closed now.
