### ISSUE TITLE
rdseed已不再维护

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#182]
https://ds.iris.edu/ds/nodes/dmc/software/downloads/rdseed/

rdseed 软件已经不再维护。

SAC 手册里依然保留 rdseed 的用法，但需要添加一个note，警告用户 rdseed 已经不再维护。

**Comment by core-man** [comment]
参考 https://seismo-learn.org/seismology101/seismology/data-format/#miniseed
