### ISSUE TITLE
重排安装章节

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#184]
最初由 @wangliang1989 在https://github.com/seisman/SAC_Docs_zh/pull/158#issuecomment-823751372提出：

> 删除了修改环境变量的内容，因为不同的操作系统的环境变量修改是雷同的，应该放在一起写，减少文字量。即打算把修改环境变量的内容改为和Linux 安装、Mac 安装并列的单独一节。

合并Linux和macOS里的**配置变量**和**启动SAC**到新的小节：
- Linux: [配置变量](https://seisman.github.io/SAC_Docs_zh/install/linux-install/#id7)、[启动SAC](https://seisman.github.io/SAC_Docs_zh/install/linux-install/#sac)
- macOS: [配置变量](https://seisman.github.io/SAC_Docs_zh/install/macOS-install/#id4)、[启动SAC](https://seisman.github.io/SAC_Docs_zh/install/macOS-install/#sac)

---

按照安装二进制包和源码包分两小节，而不是macOS和Linux两小节？

**Comment by seisman** [comment]
我目前更倾向于分成完全独立的四个小节：

- Linux 二进制安装
- Linux 源码安装
- macOS 二进制安装
- macOS 源码安装

至于重复的部分，写到单个文件里，直接 `.. include` 即可

**Comment by core-man** [comment]
> 我目前更倾向于分成完全独立的四个小节：
> 
> * Linux 二进制安装
> * Linux 源码安装
> * macOS 二进制安装
> * macOS 源码安装
> 
> 至于重复的部分，写到单个文件里，直接 `.. include` 即可

okay~

----

- 申请 SAC
- Linux 二进制安装
- Linux 源码安装
- macOS 二进制安装
- macOS 源码安装
- 配置环境变量 （**启动SAC**放到**配置环境变量**）

@seisman 是这个意思吗？

**Comment by core-man** [comment]
@wangliang1989 你想继续安装章节的完善工作吗？

**Comment by wangliang1989** [comment]
> @wangliang1989 你想继续安装章节的完善工作吗？

具体要我做什么？
刚刚你们往master分支添加了内容，如果修改了的文件在dev分支也修改了，会很不好处理

**Comment by core-man** [comment]
> > @wangliang1989 你想继续安装章节的完善工作吗？
> 
> 具体要我做什么？

- 首先是我们可以通过一个PR确定并修改安装部分的章节结构
- 然后，你可以继续把 #158 里的非 v102 相关的修改在新目录确定后，重新提交一个或多个小的 PR（如 #179）

> 刚刚你们往master分支添加了内容，如果修改了的文件在dev分支也修改了，会很不好处理

现在master的修改会通过 #174 手动merge到dev分支。直接涉及 v102 的修改再说吧，每次需要修改的时候，我们新建issue好好讨论后再搞。

**Comment by wangliang1989** [comment]
不管怎么讨论，只要出现了这种情况会非常麻烦

**Comment by core-man** [comment]
> 不管怎么讨论，只要出现了这种情况会非常麻烦

维护者麻烦一点，用户体验好点。

**Comment by core-man** [comment]
我们在确定新章节后，还需要完善申请一节 (如 https://github.com/seisman/SAC_Docs_zh/pull/190#issuecomment-824605850)

> 这个文件其实需要彻底改。Linux和Mac都可以用二进制包和源代码。Cygwin的还有没有，我不知道。用二进制包，sac的静态库可能用不了

**Comment by core-man** [comment]
> > 我目前更倾向于分成完全独立的四个小节：
> > 
> > * Linux 二进制安装
> > * Linux 源码安装
> > * macOS 二进制安装
> > * macOS 源码安装
> > 
> > 至于重复的部分，写到单个文件里，直接 `.. include` 即可
> 
> okay~
> 
> * 申请 SAC
> * Linux 二进制安装
> * Linux 源码安装
> * macOS 二进制安装
> * macOS 源码安装
> * 配置环境变量 （**启动SAC**放到**配置环境变量**）
> 
> @seisman 是这个意思吗？

Ping @seisman for comments.

**Comment by wangliang1989** [comment]
他意思是用重复的部分写成函数，需要的时候调用

**Comment by wangliang1989** [comment]
master和dev分支改了同一个文件，今后合并的时候会很麻烦。你们应该慎重考虑 @core-man @seisman

**Comment by core-man** [comment]
> 他意思是用重复的部分写成函数，需要的时候调用

Okay. 整个安装章节就四个部分：

- Linux 二进制安装
- Linux 源码安装
- macOS 二进制安装
- macOS 源码安装

**Comment by wangliang1989** [comment]
这个issue似乎已经修改完成了。但是似乎你们没有讲如果用二进制包，sac的库可能无法使用。
这点应该补充上。我的建议是在二进制安装那里加一个attention或者caution。我不是很分得清这两个英语单词的区别/

顺便一提，之前的警告还是注意是一个跟卡通的形象，我比较喜欢那个。
