### ISSUE TITLE
简化 SAC 简介章节

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#187]
[SAC简介](https://seisman.github.io/SAC_Docs_zh/introduction/)每小节都很简单，建议整合一下，减少左侧level 2 目录数量，避免用户点击很多次。具体意见我再想想

**Comment by wangliang1989** [comment]
我认为没有必要。

如果合并为一节，用户是不需要点击了，但是需要下拉。

**Comment by core-man** [comment]
> 我认为没有必要。
> 
> 如果合并为一节，用户是不需要点击了，但是需要下拉。

每节都比较短，合并后下拉也还好啦。一般3页之内阅读起来都还可以。

**Comment by core-man** [comment]
这四节合并成一节？ @seisman 你觉得呢？

- SAC 是什么？
- SAC 发展史
- SAC 变体
- SAC 邮件组
