### ISSUE TITLE
修改目录层级？

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#188]
感觉教程部分目录太长了：
![content](https://user-images.githubusercontent.com/50591376/115660912-4046a100-a36f-11eb-8a65-76e6286705b6.png)

这样如何？
- SAC 入门：包含前三章
- SAC 进阶：后面章节
- 命令手册
- 附录

**Comment by seisman** [comment]
改成入门和进阶是OK的，但是我觉得至少学了前5章才能算是入门。

**Comment by core-man** [comment]
> 改成入门和进阶是OK的，但是我觉得至少学了前5章才能算是入门。

okay
