### ISSUE TITLE
未整理的命令

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#19]
下面列出手册中未整理的命令，其中有些命令很少用到，有些命令无法正常工作。有兴趣的可以测试下面的命令，翻译整理并提交PR：
- [x] 3c
- [x] commit, recalltrace, rollback
- [x] depmec
- [ ] plotctable
- [x] mat
- [x] `readcss` (由 @PeterPanwl 负责)
- [x] ~~readdb~~
- [ ] readgse
- [ ] readsuds
- [x] writecss  (由 @PeterPanwl 负责)
- [ ] writegse
- [ ] writesdd
- [ ] pickauthor
- [ ] pickphase
- [ ] pickprefs

**Comment by wangliang1989** [comment]
READDB:
Reads data from Oracle database into memory.
As of v101.5, the Oracle database has been removed from the distribution.
没有必要写了吧？

**Comment by wangliang1989** [comment]
WRITECSS 我准备去写，这个星期剩下几天我要去香港，晚上没事写写
