### ISSUE TITLE
删除一级目录名中的SAC

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#197]
几乎每个目录都带SAC，感觉不够简洁。即使不加 SAC 也很清楚与 SAC 相关。例如，
- [脚本中调用 SAC](https://seisman.github.io/SAC_Docs_zh/call-in-script/)可以改为**脚本调用**
- [SAC I/O](https://seisman.github.io/SAC_Docs_zh/sacio/) -->> 输入/输出
- 其他直接去除 SAC

**Comment by seisman** [comment]
OK

**Comment by wangliang1989** [comment]
我更喜欢以前的样子。这样改了后主题不明确。

**Comment by core-man** [comment]
> 我更喜欢以前的样子。这样改了后主题不明确。

我觉得删了sac，理解起来没问题啊。现在的目录有点繁琐了。

**Comment by wangliang1989** [comment]
我的态度依然是保持原样，如果@seisman决定改就改

**Comment by seisman** [comment]
我觉得改或者不改没啥区别。个人倾向于不改。

**Comment by core-man** [comment]
Okay, 2 v.s. 1. Let's keep it as its origin.
