### ISSUE TITLE
更新 README 中的许可协议

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#198]
- badge 移动到顶部
- CC BY-NC-SA 3.0 CN 还是 CC BY-NC 4.0？
- 需要保留脚本许可 CC0 1.0 吗？

**Comment by seisman** [comment]
> * badge 移动到顶部

yes

> * CC BY-NC-SA 3.0 CN 还是 CC BY-NC 4.0？

4.0

> * 需要保留脚本许可 CC0 1.0 吗？

yes
