### ISSUE TITLE
去除数据获取章节

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#200]
地震学数据下载技术不断更新，如果我们要维护[数据获取](https://seisman.github.io/SAC_Docs_zh/appendix/data-fetch/#)的话，建议移动到其他网站统一维护，如 https://github.com/seismo-learn/seismology101/ (https://github.com/seismo-learn/seismology101/issues/308)

**Comment by seisman** [comment]
这一节只是提供信息，并不提供软件的具体使用方式。

**Comment by core-man** [comment]
> 这一节只是提供信息，并不提供软件的具体使用方式。

我们留着这个issue吧，直到我们在其他网站搞定了数据下载指南，然后在这里加个链接就行了。目前这些信息基本都需要在计划的指南中出现。

**Comment by seisman** [comment]
OK

**Comment by wangliang1989** [comment]
这一节不但要保留，而且必定要新增大量内容。因为新版sac可以申请数据了

**Comment by core-man** [comment]
> 这一节不但要保留，而且必定要新增大量内容。因为新版sac可以申请数据了

不建议使用 SAC 下载数据。下载数据的方法很多，需要很详细的教程，但是不应该是sac手册里。

**Comment by wangliang1989** [comment]
你还没用过，你怎么知道不好用呢？而且这是sac手册，就是写sac。

如果确实是数据处理该用obspy了，sac就用来标到时就好了。那整个这个手册都不用写了。

**Comment by core-man** [comment]
> 你还没用过，你怎么知道不好用呢？而且这是sac手册，就是写sac。

sac 可以下数据，这可以在sac命令和入门中加。我们现在不是说的附录里的数据下载汇总吗？这部分内容与sac无关啊。这部分内容确实很重要，如你所说需要加很多内容，我们需要好好维护。我建议是在其他手册，而不是放在sac手册里。

现在大部分数据下载都是基于fdsn服务，很多下载工具非常方便，而且是开源的，如sod，obspy。我们组有人试过sac下数据，并没有这几个好用。

> 如果确实是数据处理该用obspy了，sac就用来标到时就好了。

现在我和@seisman确实是这么做的了。

> 整个这个手册都不用写了。

手册当然需要写，一来我们还需要用sac，二来很多老用户还没用obspy，三来手册有很多数据处理和分析原理，信号处理通用的，很有参考价值。

**Comment by wangliang1989** [comment]
即便如此，数据获取这一部分仍然可以保留。

**Comment by core-man** [comment]
> 即便如此，数据获取这一部分仍然可以保留。

是要保留一定内容，但要简化。等我们构建好数据获取和下载手册后（计划在https://seismo-learn.org/seismology101/ 或 https://seismo-learn.org/seismology/), 加上链接即可。

**Comment by wangliang1989** [comment]
我还是不能接受。sac手册并不是seismolearn的一部分。sac手册应该当最是一本书来看待，数据申请放在附录里是很合适的。这里没有写台湾的数据中心，其实都可以加上。

**Comment by core-man** [comment]
> 我还是不能接受。sac手册并不是seismolearn的一部分。sac手册应该当最是一本书来看待，数据申请放在附录里是很合适的。这里没有写台湾的数据中心，其实都可以加上。

这个 issue 会一直 open 到我们开始在 seismo-learn 里搞定数据获取和下载部分，暂时优先级别比较低。以后再具体讨论吧。

**Comment by wangliang1989** [comment]
I suggest close the issue

**Comment by core-man** [comment]
> I suggest close the issue

we may want to keep this issue open since this section also needs updating even if we try to maintain it for a long time.

**Comment by wangliang1989** [comment]
为什么seismolearn要写的，其他项目就不能写了呢？

**Comment by wangliang1989** [comment]
这样对sac手册是不公平的。现在sac手册其实已经非常完整了。sac周边的东西写一写很合理。seismolearn的内容以后肯定会有和sac手册有交集的地方。难道都要从sac手册删除吗？以后seismolearn的软件部分可能要写sac安装。那sac手册就把sac安装删掉吗？

**Comment by core-man** [comment]
> 为什么seismolearn要写的，其他项目就不能写了呢？

可以写啊，但是这一节需要完善。我们open这个issue直到有人完善这一节。

**Comment by core-man** [comment]
> 这样对sac手册是不公平的。现在sac手册其实已经非常完整了。sac周边的东西写一写很合理。seismolearn的内容以后肯定会有和sac手册有交集的地方。难道都要从sac手册删除吗？

我们可以保留sac里数据下载章节，但可以完善和简化。打开一个issue并不一定要解决，我们可以开着它，与其他issue保持link，以便我们不要忘记，在其他issue搞定后再做点啥。你觉得呢？

> 以后seismolearn的软件部分可能要写sac安装。那sac手册就把sac安装删掉吗？

一般有中文手册的软件，我们会直接链接到手册，而不会重写。

**Comment by core-man** [comment]
@wangliang1989 @seisman I close this issue, but please remember to update this chapter when we are avaiable.
