### ISSUE TITLE
寻找minted替代品

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#21]
minted可以实现代码的语法高亮，但有两个已知缺点：
1. 依赖于外部命令`pygments`
2. 编译速度慢

**Comment by wangliang1989** [comment]
你已经排除了哪些抄录环境？

2015-08-18 23:09 GMT+08:00 Dongdong Tian notifications@github.com:

**Comment by seisman** [comment]
verbatim肯定不行，完全没有语法高亮。

listings作为备选，之前用的就是listings，但是对其高亮不太满意，才换了minted
