### ISSUE TITLE
解释源代码和二进制安装

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#217]
Originally posted at https://github.com/seisman/SAC_Docs_zh/pull/210#issuecomment-825482884:

> > > 有没有解释什么是源代码安装，什么是二进制安装？区别是什么？
> > 
> > 
> > 好的，可以在[首页](https://sac-docs-zh-qf26mmsd6-seisman.vercel.app/install/)讲一下。
> 
> 我的建议是添加caution，就说如果不知道二进制和源代码的区别，应该去看什么什么

为了使 #210 更简单、更快被接受，建议将此修改单独提交。

**Comment by seisman** [comment]
Can we close the issue?

**Comment by core-man** [comment]
I am okay to close it, since I think most of us should know the difference between source and binary if we learn basic computer skill in the university. but Ping @wangliang1989 for comment.
