### ISSUE TITLE
write 命令的segy选项没有说明

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#242]
如题，同时适用于101.6a和102，两个版本的官方差异为，102版的manual的唯一更新是针对segy选项删除了一句话“The SCALE field in SAC is ignored.”，但是相关其他叙述似乎说明scale对segy数据非常重要，不解

**Comment by seisman** [comment]
我觉得很少会有人用 SAC 读取 SEG-Y 文件，而且整个 SAC 软件中只有 read 和 write 命令提到了 SEGY。

建议直接删除手册中所有 SEGY 相关的内容。

**Comment by wangliang1989** [comment]
> 我觉得很少会有人用 SAC 读取 SEG-Y 文件，而且整个 SAC 软件中只有 read 和 write 命令提到了 SEGY。
> 
> 建议直接删除手册中所有 SEGY 相关的内容。

已经写了的保留？

**Comment by seisman** [comment]
SEGY相关的都可以删了

**Comment by wangliang1989** [comment]
> SEGY相关的都可以删了

好吧
