### ISSUE TITLE
Release v4.2

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#244]
计划这周发布 v4.2 (SAC v101.6a 的最后一个版本)。请确认是否有其他需要在 v4.2 之前解决的 issue。

**Comment by core-man** [comment]
貌似没有必须完成的 issue，我们定在北京时间6月12日（周六）发布吧？在这之前可以快速浏览一下文档。

**Comment by seisman** [comment]
Sounds good to me.

**Comment by core-man** [comment]
> @core-man 你负责发布 v4.2?

okay.

**Comment by wangliang1989** [comment]
> > @core-man 你负责发布 v4.2?
> 
> okay.

进展怎样

**Comment by core-man** [comment]
> > > @core-man 你负责发布 v4.2?
> > 
> > 
> > okay.
> 
> 进展怎样

明晚发布？

**Comment by core-man** [comment]
#246 明天merge并发布pdf，即可进入102了。
