### ISSUE TITLE
增加 SACtools 至SAC 相关工具？

### ISSUE THREAD

**Issue by core-man** [seisman/SAC_Docs_zh#256]
https://github.com/seisman/SACtools

**Comment by seisman** [comment]
https://seisman.github.io/SAC_Docs_zh/sacio/sacio-in-c/ 已经在这里提到了。

SACtools 目前处于无维护状态，且这些工具完全可以通过 ObsPy 用更简单的命令实现，感觉没有继续维护的意义。
