### ISSUE TITLE
文档代码风格

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#28]
整个文档应统一代码风格，具体风格暂定如下，如有异议，欢迎指出：
- 每行不超过72字符（特殊情况除外）；
- 物理量及单位：使用`siunitx`宏来处理数字与单位之间的间隔
- 双引号不应直接输入，左双引号用两个倒引号代替，右双引号用两个单引号代替
- 小括号使用中文括号
- 在遇到选项或参数等，尽量用`\texttt`，特殊情况下用`\verb||`
- `\ref`、`\verb`、`\nameref`等在前后有中文的情况下，应该各加一个空格，例如`中文 \ref{xxx} 中文`

**Comment by wangliang1989** [comment]
为什么关闭呢?
可否考虑在仓库里保留一个文档专门写这个？
