### ISSUE TITLE
增加数据获取一节

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#288]
建议将“第一部分 SAC入门”下的“SAC数据处理”下的“数据申请”一节迁移为“第一部分 SAC入门”下的“数据获取”，放在“SAC文件格式”之后，并做针对102版进行修改。

你们觉得好吗？

https://github.com/seisman/SAC_Docs_zh/pull/260
https://github.com/seisman/SAC_Docs_zh/issues/149

**Comment by seisman** [comment]
申请数据的方式有很多，SAC手册中不会都介绍这些数据申请方式，所以没有必要将申请数据作为单独的一章。

**Comment by wangliang1989** [comment]
官方手册就是这样的
<img width="306" alt="image" src="https://user-images.githubusercontent.com/12059719/154197771-a9d32329-5f39-4563-a017-be64b6c28598.png">

**Comment by seisman** [comment]
中文手册没必要与英文手册一致。另外，等有了具体内容之后再考虑是否要作为单独的一章也不迟。

**Comment by wangliang1989** [comment]
好吧那我就先往现在的那个小节添加内容

Dongdong Tian ***@***.***>于2022年2月16日 周三下午10:17写道：
