### ISSUE TITLE
数学模式中数字与单位的间隔

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#30]
目前文档中在设计数字与单位之间没有间隔，不符号标准。考虑采用[siunitx](https://www.ctan.org/pkg/siunitx)宏包解决这一问题。

参考：
1. http://tex.stackexchange.com/questions/107818
2. http://tex.stackexchange.com/questions/20962
3. http://tex.stackexchange.com/questions/2248

**Comment by wangliang1989** [comment]
数学格式的问题，那个什么数学联合会应该有个标准，比如圆周率的pi和一般的pi不一样，等等都有规定，应该有一个完整的规定

**Comment by seisman** [comment]
这个Issue要解决的是物理量的数字和单位之间的空格问题，其他问题遇到再说吧。

**Comment by wangliang1989** [comment]
我觉得属于一类问题吧，首先找到国际标准，再看哪个宏包符合国际标准，你看刘海洋240页第一句话引用的两篇文章114和261
114：http://www.iso.org/iso/catalogue/catalogue_tc/catalogue_tc_browse.htm?commid=46202
261：http://physics.nist.gov/cuu/pdf/sp811.pdf

**Comment by seisman** [comment]
太长。。。

**Comment by wangliang1989** [comment]
好吧，确实是数字和单位之间应该有个间隔
http://tex.stackexchange.com/questions/20962/should-i-put-a-space-between-a-number-and-its-unit
这个里面，我更倾向于数字和omi间隔宽一点的那种

**Comment by seisman** [comment]
还是使用更多人推荐的siunitx吧

**Comment by wangliang1989** [comment]
好吧

**Comment by seisman** [comment]
PR #31 已经完成了大部分，剩下的遇到了再修订。本Issue暂时不关闭。
