### ISSUE TITLE
在Rust中读写SAC文件

### ISSUE THREAD

**Issue by SanmerDev** [seisman/SAC_Docs_zh#319]
有没有考虑增加 Rust 实现的 SAC I/O ？我写好了第一个版本:
-  [libsac](https://github.com/SanmerDev/libsac)

还有借助它通过 JNI 实现的 Kotlin 版本:
- [libsac-jni](https://github.com/SanmerDev/libsac-jni)

**Comment by seisman** [comment]
欢迎PR

**Comment by wangliang1989** [comment]
本文档应该是只介绍这些软件的使用，并不维护这些软件。如果你希望本文档进行介绍，你想要自己写相关文字，然后发PR

**Comment by SanmerDev** [comment]
我已经停止维护相关库了，所以就不向文档提交PR了
