### ISSUE TITLE
增加讲授如何申请数据的章节

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#34]
主要讲IRIS申请数据的各种方式，也包括其他机构的（如果可能的话）
要把这部分放在哪里？

**Comment by seisman** [comment]
在“SAC数据处理”一章的开头简单列举从IRIS申请数据的几种工具。具体工具如何使用放在附录中单独作为一章。

**Comment by wangliang1989** [comment]
OK

**Comment by wangliang1989** [comment]
请加上inprogress标签

**Comment by wangliang1989** [comment]
https://github.com/seisman/SAC_Docs_zh/pull/53
考虑增加数据中心的申请方法
