### ISSUE TITLE
删除命令中的“相关命令”部分

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#36]
在每个命令的说明中，基本都会提到该命令的相关命令，所以“相关命令”这一小节可以删除。

**Comment by wangliang1989** [comment]
建议保留，想看的话，可以点，就快一些，保留也没什么坏处

**Comment by seisman** [comment]
这些相关的命令都会出现在命令的说明中，而且在说明中这些相关命令也是有超链接的，需要跳转的话在说明中直接点也是一样的。

想要删除主要是两个原因：
1. 单独列出来，有点与说明中的超链接重复了；
2. 删除的话，每个命令可以省3行，文档的页数应该可以少挺多；

**Comment by wangliang1989** [comment]
这倒也是

**Comment by seisman** [comment]
如果你也觉得没什么意见的话，那就确认删除了。

**Comment by wangliang1989** [comment]
OK

**Comment by seisman** [comment]
Fixed in 13a6323f9b7fb6db1a5502b09a48d798c50bdca8
