### ISSUE TITLE
rdseed用法

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#38]
`rdseed`是最常用的格式转换工具，可以简单介绍其用法，放在`SAC相关工具`一章

**Comment by wangliang1989** [comment]
我是觉得报错信息比较难处理，我就见到报错，数据就不用

**Comment by wangliang1989** [comment]
https://github.com/seisman/SAC_Docs_zh/pull/49

**Comment by seisman** [comment]
Fixed in PR #49
