### ISSUE TITLE
convert命令的简单用法

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#4]
SAC可以输出图像为PS或PDF格式，有些情况下需要将其转换为常见的图片格式，如JPG或PNG。

convert命令是Linux下比较通用且强大的图片格式转换命令，可以对该命令做简单介绍。

可以参考seisman博客中的[《图像格式转换工具convert》](http://seisman.info/convert-and-ps2raster.html)

**Comment by junlysky** [comment]
OK

发自我的 iPhone

**Comment by seisman** [comment]
Completed.
