### ISSUE TITLE
plotpk的若干问题

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#56]
1. `BELL ON|OFF`选项是否可用？
2. `REFERENCE ON|OFF|v`选项是否可用？
3. `RELATIVE|ABSOLUTE`的解释有误？
4. `SAVELOCS`选项是否有效？
5. `MARKALL`的有效性？

**Comment by wangliang1989** [comment]
plotpk bell on没有声音
reference和relative的缩写在手册里都是r
暂存块变量是什么

**Comment by seisman** [comment]
See PR #57

**Comment by seisman** [comment]
`BELL ON`选项我记得以前是有用的，现在不知道为何已经无法使用了。

**Comment by wangliang1989** [comment]
可能是操作系统不兼容？

**Comment by seisman** [comment]
`BELL`的问题加了个脚注说明了一下。

**Comment by seisman** [comment]
Fixed in #57.
