### ISSUE TITLE
在Fortran程序中读写SAC文件

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#6]

**Comment by wangliang1989** [comment]
为什么需要用FORTRAN读SAC？

**Comment by seisman** [comment]
因为有人喜欢用fortran写程序处理数据，这就涉及到如何在fortran中读写sac了。

**Comment by wangliang1989** [comment]
你的意思是脱离SAC，读取sac文件？何必这样呢？难道还要自己去实现SAC的功能？

**Comment by seisman** [comment]
SAC只能用于完成简单的数据预处理，无法用于实际的数据分析。就像gcap，实际上就是在C程序中读入SAC文件并处理，像fk中也涉及到写SAC格式的文件。所以，在C/Fortran中读写SAC文件是常用需求。

**Comment by wangliang1989** [comment]
在这里要做的，仅仅是用FORTRAN程序把SAC数据读入内存？

**Comment by seisman** [comment]
是，可以参考手册中已经完成的“在C程序中读写SAC文件”一节。只是现在Fortran没有一个已经实现的比较好的接口，所以这一部分就没有写。

**Comment by wangliang1989** [comment]
我是这样理解的：
就是写一个程序，包含两个子程序：头段相关和数据相关，然后两个子程序再包含读取功能、修改功能子程序，等等。以后的人可以依据需要自己写他们的子程序。
SAC的二进制格式和文本格式，FORTRAN应该都可以搞定吧。

**Comment by seisman** [comment]
可以这样理解，具体的可以参考Lupei Zhu的sacio。

**Comment by wangliang1989** [comment]
不需要什么IO阿

**Comment by seisman** [comment]
读写SAC文件就是实现SAC IO的功能啊。我们俩对IO的理解不一致？

**Comment by wangliang1989** [comment]
用充电宝，你觉得自己找来的数据线是IO，我觉得充电宝上已经做好的USB接口是IO。

**Comment by seisman** [comment]
在已有接口的前提下，想要介绍的是如何在程序中直接调用接口来读写SAC文件。Lupei Zhu的sacio已经实现好了接口，所以“在C程序中读写SAC文件”一节实际上是在介绍如何调用他提供的接口。

Fortran目前没有提供一个比较好的接口，所以这一节暂时没法写。

**Comment by wangliang1989** [comment]
等写完css，我试一试

**Comment by seisman** [comment]
你可以把css已写的部分发个PR过来。

**Comment by wangliang1989** [comment]
https://github.com/PeterPanwl/SAC_FORTRAN_interface
