### ISSUE TITLE
如何处理SAC软件的BUG

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#61]
SAC软件目前还有大量bug，尤其是某些不太常用的命令。这些BUG该如何处理？
1. 是否要将BUG写到文档中？
2. 以何种方式写到文档中？
3. 若新版本SAC中已经修复了此BUG，文档中是要删除此BUG的描述？还是保留BUG并注明哪些版本有BUG？

**Comment by wangliang1989** [comment]
1发现了当然要写
2看bug具体情况
3后者
