### ISSUE TITLE
该介绍ppk p 3 r m还是a m

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#63]
1多个数据一起标定的时候，写入t1的是鼠标在的那个数据的参考时间，如果有数据的参考时刻和这个数据的不一样，就会出错

2初学者没有改参考时间为一致，数据又有间断，那么在多个数据标定时可能波形对齐不是用户想象的那样

3多数人比如我不会第一次看就看命令的详细解释，我们是否需要考虑在数据处理介绍的时候把ppk p 3 r m换乘a m然后提示参考时刻要一样，否则时间就不对？

**Comment by seisman** [comment]
1. 是
2. 参考时间不一致的话，用`markall`标定总是错的
3. 就拾取三分量数据而言，`ppk p 3 r m`的确不如`ppk p 3 a m`

**Comment by wangliang1989** [comment]
https://github.com/seisman/SAC_Docs_zh/pull/64

**Comment by seisman** [comment]
Fixed in #64, now closed.
