### ISSUE TITLE
merge脚本

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#67]
从SEED数据中提取出SAC文件之后，可能需要对数据做merge，需要写一个脚本，对所有的数据做遍历，以实现merge功能。

**Comment by wangliang1989** [comment]
如果数据有重叠，又不相同，怎么处理合适？

**Comment by seisman** [comment]
出现这种问题的原因尚不清楚。理论上，这种情况下数据有冲突，所以肯定至少有一段数据是错的，在这种情况下强行将数据merge在一起，总觉得是有问题的。

**Comment by wangliang1989** [comment]
出现这种情况，返回给用户，用户决定怎么办
选项1 退出，数据回到原始状态
       2 求平均
……

**Comment by seisman** [comment]
用户要根据自己的理解决定怎么改写脚本。

**Comment by wangliang1989** [comment]
对Z分量数据merge：
1搜寻所有Z分量数据
2判断是否同一个台有多个数据，如果是执行merge，如果不是这个文件直接重命名
如果需要其他分量，程序员可以自己改

**Comment by seisman** [comment]
Fixed in e0cc2c506a8365b02d7cc5821630e5776722a0bc and 8b046b6d684f9478e6ec394dd44ffa1d0aa929bc
