### ISSUE TITLE
如何处理saclst返回的头段不准的问题

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#75]
saclst返回的头段b和e的小数点后的部分不准。用这些值做数据截窗的窗口，可能出现越界。

**Comment by seisman** [comment]
通常情况下，saclst返回的B值与E值的差别很少，仅仅是小数点的最后一位有区别。这不会影响到数据截窗。

假设B为9.46，delta为0.01，则用 `cut 9.458 e`也是可以正常截取的。

仅当B值很大时会出现问题，比如B等于1234567.89，就会出现该问题。但与此同时，SAC的其他命令都会出现类似的问题，因而对这种情况不做考虑。

**Comment by wangliang1989** [comment]
OK
