### ISSUE TITLE
处理小修改地方式

### ISSUE THREAD

**Issue by wangliang1989** [seisman/SAC_Docs_zh#81]
我建议，**固定地**把小修改和编译错修改放到fix分支。
# . 所有人做了新的小修改或者编译错修改后就尝试pr到seisman的fix分支在fix分支里。
# . 如果seisman没有fix分支则发issue请求建立fix分支。
# . 发现编译错，修改后，seisman把fix分支merge到master，并且删除fix分支。
# . fix分支在做的任何commit，需要最终表示在master历史中的用中文/英文说明，不需要的就叫fix

**Comment by seisman** [comment]
不影响编译的小修改，可以直接PR到fix分支中；影响到编译的小修改，直接PR到master分支。
