### ISSUE TITLE
为项目增加License

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#82]

**Comment by wangliang1989** [comment]
http://www.ruanyifeng.com/blog/2011/05/how_to_choose_free_software_licenses.html

**Comment by wangliang1989** [comment]
我是觉得代码部分apacha比较好，也比较现实，文章部分就和博客一样就好了

**Comment by seisman** [comment]
http://choosealicense.com/

**Comment by wangliang1989** [comment]
cc,脚本代码apacha

**Comment by seisman** [comment]
CC BY-NC-SA 4.0 + BSD

**Comment by seisman** [comment]
https://github.com/seisman/SAC_Docs_zh/blob/master/LICENSE

**Comment by seisman** [comment]
4a2c30628cb6043cedc0cea21b4c7ecec1d9cb2a
