### ISSUE TITLE
更新对SAC/BRIS的说明

### ISSUE THREAD

**Issue by likueimo** [seisman/SAC_Docs_zh#96]
抱歉本來要pull但還是不夠熟悉
我用繁體中文打修改內容，怕用字不是簡體慣用字詞
可能要交給大家幫忙修成適合簡體常用詞(?

SAC变体 這個section

\item[MacSAC]       也称为SAC/BRIS，仅可在Mac OS下使用。该变种由
                    10.6d Fortran源码衍生而来，后期与10.6f集成，
                    其功能是SAC/IRIS功能的超集。相对于SAC/IRIS的最主要
                    扩展在于宏语言功能的增强以及处理台阵数据的能力。
                    其作者为
                    \href{http://www1.gly.bris.ac.uk/~george/gh.html}{George Helffrich}。

我建議可以改

\item[SAC/BRIS]       也可称为MacSAC，主要設計給Mac OS，除了提供Mac OS下編譯好安裝包外，還可安裝在其他linux系統(需使用網頁上提供shell script自行編譯，使用時要注意endian問題，因為Mac OS為big-endian)。该变种由
                    10.6d Fortran源码衍生而来，后期与10.6f集成，
                    其功能是SAC/IRIS功能的超集。相对于SAC/IRIS的最主要
                    扩展在于宏语言功能的增强以及处理台阵数据的能力之外，還可以直接讀取miniseed檔案(執行sac後，read mseed miniseed檔名)。
                    其作者为
                    \href{http://www1.gly.bris.ac.uk/~george/gh.html}{George Helffrich}。

**Comment by seisman** [comment]
我会在确认之后更新。
