### ISSUE TITLE
Mac 下源码编译后的二进制文件执行出错

### ISSUE THREAD

**Issue by seisman** [seisman/SAC_Docs_zh#98]
执行后出现 abort 错误，原因未知。

**Comment by likueimo** [comment]
可以寫詳細是Mac OS哪一版本嗎(筆電對吧)
然後是從 IRIS 申請 Mac 版編譯好的sac對吧
之前學弟電腦上感覺沒遇到問題

**Comment by seisman** [comment]
1. 直接使用 IRIS 提供的Mac 预编译版是没有问题的
2. 我目前使用的是 Mac OS 10.11.5，编译源码生成的 SAC 有问题。
3. 当时写文档的时候是在 10.10 下做的测试，编译源码生成的 SAC 应该是没有问题的

**Comment by likueimo** [comment]
哦哦 好 我也沒編譯過sac
剛剛沒看清楚標題，原來是編譯後出錯
抱歉抱歉

**Comment by wangliang1989** [comment]
102版已经没有问题了
