### ISSUE TITLE
提議把手冊轉換成gitbook

### ISSUE THREAD

**Issue by likueimo** [seisman/SAC_Docs_zh#99]
在gitbook上內文可放github

在gitbook同時可以使用網頁、pdf、epub格式發布手冊

在每頁面底下也可以讓網頁留言討論(我有看過但不普遍)

gitbook中文說明
https://www.gitbook.com/book/wastemobile/gitbook-chinese/details

缺點是從 tex 轉換成網頁Markdown 
可能需要人工慢慢來
(網路上有現成 latex to Markdown工具，但不確定轉換效果)

等我畢業時候或許我可以來幫忙
不知道各位覺得如何?

**Comment by wangliang1989** [comment]
有个网络在线版有好处：
1. 让读者能即时更新
2. 回答别人问题时，想直接告诉他手册上哪里就有，只有pdf版相对地没有那么方便
不好的是: 这个工作量可能很大，不过改成markdown，也许pandoc可以

**Comment by likueimo** [comment]
對我而言比較方便是
可以針對章節每一頁有疑問地方
在下方留言提出問題或是更正

而且在手機或平板等移動端也較方便

**Comment by seisman** [comment]
使用gitbook的优点：
1. 有在线版，epub，mobi，pdf等格式
2. 源码是markdown格式，与tex文件相比更易读易写
3. 方便用户评论，以不断更新

缺点：
1. gitbook生成的网页默认托管在 username.gitbooks.io 上，这个网站在大陆的访问速度很慢
2. 我使用过 gitbook提供的本地编辑器，无法完全理解其如何与远程进行同步，尤其是在遇到冲突时，觉得很混乱。
3. gitbook的评论要求gitbook账户，所以评论其实没有想象的那么方便，当然gitbook也支持使用disqus等第三方评论系统，所以应该没有太大问题
4. 从markdown转换成PDF，其效果必然没有从tex转换PDF效果好

一点想法：
1. 网页版有很多好处，值得做
2. 如缺点1所说，gitbook默认的托管服务器速度慢，因而不建议使用。我的建议是使用gitbook命令行，将markdown文件转换成网页，pdf等格式，然后托管到github pages上。
3. 除了gitbook之外，或许还可以考虑使用gmt手册目前采用的sphinx，当然也许还有其他更好的工具。

**Comment by eminenceG** [comment]
网页版的好处是有评论功能，这样在阅读的时候出现问题可以提出，也方便我们完善内容.
Github相关网页之前是被墙，后来在科大校园网内可以打开，但是既然网速很慢那么托管在gitbooks.io上肯定不行，大部分人都不翻.
可以考虑制作更方便阅读的在线版

**Comment by seisman** [comment]
1. 既然大家都觉得需要一个在线版，那就把在线版提上日程吧
2. 使用 gitbook 生成的网页，可以托管在任意地方，所以是选择 gitbooks.io 还是 github.io 甚至放在单独的服务器上，都没有问题。我更倾向于直接使用 gitbook 提供的命令行工具，然后将生成的网页托管在 github.io 上
3. markdown 转 PDF 的效果肯定没有 latex 转 PDF 的效果好，所以我建议在维护 markdown 版本的同时，保留并维护 LaTeX 版，等到一切稳定下来之后再考虑是否要舍弃 LaTeX 版
4. 在正式开始网页版之前，也许我们需要把 v3.6 先发布出去

**Comment by wangliang1989** [comment]
LATEX转markdown怎么转？

**Comment by seisman** [comment]
试试 pandoc，估计效果不理想，因为LaTeX 中我使用了很多自定义的命令。不行的话就人工一个一个转。

**Comment by likueimo** [comment]
1. 3.6發佈大概要做哪些事情呢

**Comment by seisman** [comment]
发布的事情我来做就好。 @likueimo

**Comment by seisman** [comment]
- [ ] 发布 SAC v3.6版
- [x] 新建gitbook 分支，搭建整体框架
- [x] 生成的网页托管在 github pages

**Comment by seisman** [comment]
@likueimo 你先把自己加 contributor.tex 里，我再发布 v3.6
